name: icrm
description: A new Flutter project.

publish_to: 'none'


version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  equatable:
  cached_network_image:
  flutter_locales: ^2.0.0
  intl: ^0.17.0
  intl_phone_number_input:
  percent_indicator: ^4.0.0
  flutter_staggered_grid_view: ^0.6.1
  shared_preferences: ^2.0.12
  table_calendar: ^3.0.3
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  get_it: ^7.2.0
  image_picker: ^0.8.4+9
  path_provider: ^2.0.9
  firebase_messaging: ^11.2.4
  speech_to_text: ^5.4.0
  firebase_dynamic_links: ^4.0.8
  url_launcher: ^6.0.20
  day_night_time_picker: ^1.0.5
  mask_text_input_formatter: ^2.1.0
  currency_picker: ^2.0.8
  share: ^2.0.4
  file_picker: ^4.5.1
  lottie: ^1.2.2
  pull_to_refresh: ^2.0.0
  flutter_local_notifications: ^9.5.3+1
  avatar_glow: ^2.0.2
  webview_flutter: ^3.0.4
  teledart: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:


  uses-material-design: true
  assets:
    - assets/icons_svg/
    - assets/locales/
    - assets/png/
    - assets/json_animations/preload.json
    - assets/json_animations/swipe.json



